import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import {Space_Grotesk} from 'next/font/google'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable} h-screen font text-white flex flex-col items-center font-sans w-full`}>
        <Header />
        {children}
      </body>
    </html>
  );
}

